version: '3.9'

services:
  db:
    image: postgres
    container_name: solodevhub-db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"

  web:
    build:
      context: .
    container_name: solodevhub-web
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "13000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password

volumes:
  db_data:
